apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
 name: global-acme
 annotations:
   kubernetes.io/ingress.class: kong
 labels:
   global: "true"
config:
  allow_any_domain: true
  account_email: example@example.com
  api_uri: https://acme-staging-v02.api.letsencrypt.org/directory
plugin: acme
