values:
    ### Enviroment Settings
    environment: platform_homolog_environment
    ### Project Settings
    cluster_name: cluster-minimalista-teste-01
    owner: group:default/admin
    instance_type: t3.medium
    volume_size: 30
    keypair_name: platform_kp
    ### Network Settings
    vpc_id: vpc-051721395ecf1f7aa
    domain: vkpr.platform.vee.codes
    hostedZoneId: Z08737613ML5F3HE67WJ3
    subnet_id: subnet-04dda6147dd9410f1
    ### Ingress Settings
    ingress_window: false
    ingress_type: 
    kong_mode: 
    external_db: 
    basic_auth: 
    certmanager_window: 
    issuer_type: 
    email: 
    ### Terraform Backend Settings
    terraformStateBucketName: veecode-homolog-terraform-state
    terraformStateBucketRegion: us-east-1
    infracost: false
    ### Publish Settings
    host: github.com
    destination: veecode-homolog/cluster-minimalista-teste-01
    specPublish: ${{ parameters.specPublish | parseRepoUrl | pick('owner') }}/${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
    specPublishRepo: ${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
    specPublishBranch: 
    ### Observability Settings
    observability_window: false
    observability_grafana_url: 